# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - gfortran

submodules:
  include: all
  recursive: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/source/conf.py
