name: tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8.2]
        poetry-version: [1.1.4]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out Repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.8.2
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies frontend
      run: python -m pip install build pytest auditwheel
    - name: Build package wheel with build
      run: python -m build .
    - name: Fix wheels
      run: python -m auditwheel repair dist/*.whl
    - name: Install wheel with pip
      run: python -m pip install --no-input wheelhouse/*.whl
    - name: Run pytest
      run: pytest .
