name: tests

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-18.04
    steps:
    - name: Check out Repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.2.0
    - uses: actions/upload-artifact@v2
      with:
        name: distribution
        path: ./wheelhouse/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-18.04
    steps:
    - name: Check out Repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies frontend
      run: python -m pip install build
    - name: Build sdist with build
      run: python -m build . --sdist
    - name: Upload source package
      uses: actions/upload-artifact@v2
      with:
        name: distribution
        path: dist/

  test_wheel:
    name: Run pytest off wheel installation on ${{ matrix.os }}
    needs: [build_wheels]
    strategy:
      matrix:
        python-version: [3.8.2]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install pytest
      run: pip install pytest
    - name: Install wheel
      run: pip install wheelhouse/*.whl
    - name: Run pytest
      run: pytest test