name: tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8.2]
        poetry-version: [1.1.4]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out Repository
      uses: actions/checkout@v2
    - name: Set up Python 3.8.2
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Print Stuff with Python
      run: python -c "print('python output without poetry')"
    - name: Install poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install package with poetry
      run: poetry install
    - name: Print stuff with poetry
      run: poetry run python -c "print('python output with poetry')"
    # - name: Install AUTO-07p.
    #   run: poetry run python -m pyfurc --install-auto --use-defaults
    #   timeout-minutes: 1
    # # - name: Lint with flake8
    # #   run: |
    # #     # stop the build if there are Python syntax errors or undefined names
    # #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    # #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    # #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     poetry run pytest
